namespace RTOpenAI
open System
open System.Net.WebSockets
open System.Threading.Channels
open FSharp.Control
open RTOpenAI.Events
open RTOpenAI.Session

type MachineMsg =
    | MM_Session_Created
    | MM_Session_Ended
    | MM_EventError of ErrorDetail
    | MM_Audio of byte[]
    | MM_Text of string
    | MM_ClientEvent of  ClientEvent

module Machine =
    let processServerEvent (session: RTOpenAI.Session) (event: Events.ServerEvent) : (MachineMsg list * RTOpenAI.Session) =        
        match event with
        | Events.ServerEvent.Error e -> 
            // Handle error event (you might want to log the error or update the session state)
            [MM_EventError e.error],session

        | Events.ServerEvent.SessionCreated e ->             
            [MM_Session_Created],{session with RTSession=e.session}

        | Events.ServerEvent.SessionUpdated e ->            
            // Update session with updated session data
            let rtSession = 
                {session.RTSession with
                    model = e.session.model |> Option.orElse session.RTSession.model
                    modalities = e.session.modalities
                    instructions = e.session.instructions |> Option.orElse session.RTSession.instructions
                    voice = e.session.voice |> Option.orElse session.RTSession.voice
                    input_audio_format = e.session.input_audio_format |> Option.orElse session.RTSession.input_audio_format
                    output_audio_format = e.session.output_audio_format |> Option.orElse session.RTSession.output_audio_format
                    input_audio_transcription = e.session.input_audio_transcription |> Option.orElse session.RTSession.input_audio_transcription
                    turn_detection = e.session.turn_detection |> Option.orElse session.RTSession.turn_detection
                }
            [],{session with RTSession=rtSession}
        | Events.ServerEvent.ConversationCreated e ->
            [],session
        | Events.ServerEvent.ConversationItemCreated e ->
            [],{session with Conversation = Conversation.insertItem e session.Conversation}
        | Events.ServerEvent.ConversationItemInputAudioTranscriptionCompleted e ->
            [],{session with Conversation=Conversation.updateAudioTranscription e session.Conversation}
        | Events.ServerEvent.ConversationItemInputAudioTranscriptionFailed e ->
            [],{session with Conversation=[]}
        | Events.ServerEvent.ConversationItemTruncated e ->
            [],session
        | Events.ServerEvent.ConversationItemDeleted e ->
            [],{session with Conversation = Conversation.deleteItem e session.Conversation}
        | Events.ServerEvent.InputAudioBufferCommitted e ->
            [MM_Audio [||]],session  
        | Events.ServerEvent.InputAudioBufferCleared e ->
            [],session
        | Events.ServerEvent.InputAudioBufferSpeechStarted e ->
            [],session
        | Events.ServerEvent.InputAudioBufferSpeechStopped e ->
            [],session
        | Events.ServerEvent.ResponseCreated e ->
            [],session
        | Events.ServerEvent.ResponseDone e ->
            [],session
        | Events.ServerEvent.ResponseOutputItemAdded e ->
            [],session
        | Events.ServerEvent.ResponseOutputItemDone e ->
            [],session
        | Events.ServerEvent.ResponseContentPartAdded e ->
            [],session
        | Events.ServerEvent.ResponseContentPartDone e ->
            [],session
        | Events.ServerEvent.ResponseTextDelta e ->
            [],session
        | Events.ServerEvent.ResponseTextDone e ->
            [],session
        | Events.ServerEvent.ResponseAudioDelta e ->
            [],session
        | Events.ServerEvent.ResponseAudioDone e ->
            [],session
        | Events.ServerEvent.ResponseAudioTranscriptDelta e ->
            [],session
        | Events.ServerEvent.ResponseAudioTranscriptDone e ->
            [],session
        | Events.ServerEvent.ResponseFunctionCallArgumentsDelta e ->
            [],session
        | Events.ServerEvent.ResponseFunctionCallArgumentsDone e ->
            [],session
        | Events.ServerEvent.RateLimitsUpdated e ->
            [],session

    let logIfFalse msg r = if not r then Log.info msg
    
    ///handle events generated by machine
    let publishEvent (audioOutput:Channel<byte[]>) ws dispatch event =
        async {
            try 
                match event with 
                | MM_Audio chunk -> audioOutput.Writer.TryWrite(chunk) |> logIfFalse "dropped speaker audio" 
                | MM_Text text -> dispatch (MM_Text text)
                | MM_ClientEvent ev -> do! Pipe.sendSilent ws ev
                | MM_EventError err -> Log.error err.message
                | MM_Session_Created -> dispatch MM_Session_Created
                | MM_Session_Ended -> dispatch MM_Session_Ended
            with ex ->
                Log.exn (ex, "publishEvent")
        }
       
    let defaultMachine (_,session:RTOpenAI.Session) (event:SessionEvent) =
        match event with
        | SE_Server serverEvent -> processServerEvent session serverEvent
        | _ -> [],session
   
    let run machine dispatch (initSession:RTOpenAI.Session) =
        Session.serverEvents initSession.WsWrapper
        |> AsyncSeq.merge (Session.micEvents initSession.AudioInput)
        |> AsyncSeq.merge (Session.ticks())
        |> AsyncSeq.scan machine ([],initSession)
        |> AsyncSeq.collect(fst>>AsyncSeq.ofSeq)
        |> AsyncSeq.iterAsync (publishEvent initSession.AudioOutput initSession.WsWrapper dispatch)           

    let runDefault = run defaultMachine
    